"""Full-pipeline performance under simulated mounting errors.

.. _pipeline_val_mounting_error_results:

Full-pipeline performance under simulated mounting errors
==========================================================

This analysis compares the free-living full-pipeline validation results across
simulated lower-back sensor mounting orientations. It uses the result files
generated by :ref:`pipeline_val_mounting_error_gen`.

The main plots show signed combined DMO errors. Each box represents all
recording-level errors in the selected cohort group for one pipeline variant
and one simulated orientation.

.. note:: The combined analysis compares the recording-level aggregate DMO
    output against the INDIP reference. This is the most relevant view for
    real-world performance, where downstream users typically consume aggregates
    over full recordings.

"""

# %%
# Compared Pipelines
# ------------------
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from mobgap.plotting import move_legend_outside
from mobgap.re_orientation.pipeline import REORIENTATION_LABELS
from mobgap.utils.misc import get_env_var

algorithms = {
    "Official_MobiliseD_Pipeline": "Default",
    "Official_MobiliseD_Pipeline__reorientation": "Default + Reorientation",
    "Official_MobiliseD_Pipeline__reorientation_gsd_iluz_adaptive": (
        "Adaptive GSD + Reorientation"
    ),
}
algorithm_order = list(algorithms.values())
orientation_order = list(REORIENTATION_LABELS)

regular_walking_cohorts = ["HA", "COPD", "CHF"]
impaired_walking_cohorts = ["MS", "PD", "PFF"]

dmos = {
    "walking_speed_mps": ("Walking speed", "m/s"),
    "stride_length_m": ("Stride length", "m"),
    "cadence_spm": ("Cadence", "steps/min"),
}

# %%
# Loading The Free-Living Results
# -------------------------------
# The standard validation result loader has fixed TVS index columns. The
# mounting-error result files add ``orientation`` to that index, so we load the
# local CSV files directly here.
results_base_path = (
    Path(get_env_var("MOBGAP_VALIDATION_DATA_PATH"))
    / "results/full_pipeline_mounting_error/free_living"
)


def load_mounting_error_results() -> pd.DataFrame:
    results = []
    for folder_name, algorithm_label in algorithms.items():
        result_file = results_base_path / folder_name / "single_results.csv"
        data = pd.read_csv(result_file).assign(
            algorithm=algorithm_label,
        )
        results.append(data)
    return pd.concat(results, ignore_index=True)


def combined_error_long(data: pd.DataFrame) -> pd.DataFrame:
    results = []
    id_vars = [
        "algorithm",
        "orientation",
        "cohort",
        "participant_id",
        "time_measure",
        "recording",
        "recording_name",
        "recording_name_pretty",
    ]
    for dmo, (dmo_label, unit) in dmos.items():
        column = f"combined__{dmo}__error"
        results.append(
            data[[*id_vars, column]]
            .rename(columns={column: "error"})
            .assign(dmo=dmo_label, unit=unit)
        )
    return pd.concat(results, ignore_index=True)


free_living_results = load_mounting_error_results()
combined_errors = combined_error_long(free_living_results)

# %%
# Plot Helpers
# ------------
sns.set_context("talk")


def plot_combined_error_boxplots(
    data: pd.DataFrame,
    *,
    title: str,
) -> None:
    fig, axes = plt.subplots(
        1,
        3,
        figsize=(20, 7),
        sharex=True,
        constrained_layout=True,
    )
    for ax, (dmo_label, unit) in zip(axes, dmos.values()):
        plot_data = data[data["dmo"] == dmo_label]
        sns.boxplot(
            data=plot_data,
            x="algorithm",
            y="error",
            hue="orientation",
            order=algorithm_order,
            hue_order=orientation_order,
            showmeans=True,
            ax=ax,
        )
        ax.axhline(0, color="0.4", linewidth=1, linestyle=":", zorder=-50)
        ax.set_title(dmo_label)
        ax.set_xlabel("")
        ax.set_ylabel(f"Combined error [{unit}]")
        ax.tick_params(axis="x", rotation=20)
        ax.grid(True, axis="y", alpha=0.3)
        ax.legend(title="Orientation")

    fig.suptitle(title)
    move_legend_outside(fig, axes[-1])
    plt.show()


# %%
# All Cohorts
# -----------
# This view pools combined errors across all free-living cohorts for each
# pipeline variant and simulated orientation.

plot_combined_error_boxplots(
    combined_errors,
    title="Combined DMO errors across all cohorts",
)

# %%
# Regular-Walking Cohorts
# -----------------------
# These are the cohorts where the default Mobilise-D pipeline uses
# :class:`~mobgap.gait_sequences.GsdIluz`.

plot_combined_error_boxplots(
    combined_errors[combined_errors["cohort"].isin(regular_walking_cohorts)],
    title="Combined DMO errors in regular-walking cohorts",
)

# %%
# Impaired-Walking Cohorts
# ------------------------
# These are the cohorts where the default Mobilise-D pipeline uses
# :class:`~mobgap.gait_sequences.GsdIonescu`.

plot_combined_error_boxplots(
    combined_errors[combined_errors["cohort"].isin(impaired_walking_cohorts)],
    title="Combined DMO errors in impaired-walking cohorts",
)
