context:
  version: 4.0.1
package:
  name: python-xxhash
  version: ${{ version }}
source:
  url: https://files.pythonhosted.org/packages/f6/a5/1386f35da1475fcaeef42581deae73417c6d2a6a0b2d2e8914de18844dcd/xxhash-${{ version }}.tar.gz
  sha256: d55bf4ef10eb09b8b6866790e083d26d087d84caa3cc0946ba87c3ca7ecaf7b7
build:
  number: 0
  script: build.sh
  python:
    skip_pyc_compilation:
      - '**/*.py'
requirements:
  build:
    - python 3.13.*
    - pip
    - cross-python_${{ target_platform }} ==3.13.1
    - ${{ compiler('c') }}
  host:
    - python ==3.13.1
    - setuptools
    - pip
  run:
    - python >=3.13,<3.14
about:
  homepage: https://github.com/ifduyue/python-xxhash
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Genuine Python bindings for bundled xxHash algorithms, compiled for browser WASM
