"""
.. _gsd_misorientation_val_results:

GSD performance under simulated mounting errors
================================================

This analysis compares gait sequence detection performance across simulated
lower-back sensor mounting orientations. It uses the result files generated by
:ref:`gsd_misorientation_val_gen`.

The main plots show the per-recording/per-trial F1 score for each algorithm and
orientation. Each simulated orientation is produced by converting the TVS
recording to body frame and applying the rough mounting rotations used by the
reorientation validation.

.. note::
    The standard GSD validation remains the reference for performance under the
    default Mobilise-D mounting assumption. This page isolates orientation
    robustness and therefore only compares Python algorithms that can be rerun
    on the simulated recordings.

"""

from pathlib import Path
from typing import Literal

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from mobgap.data.validation_results import ValidationResultLoader
from mobgap.plotting import move_legend_outside
from mobgap.re_orientation.pipeline import REORIENTATION_LABELS
from mobgap.utils.misc import get_env_var

# %%
# Algorithms
# ----------
algorithms = {
    "GsdIonescu": ("GsdIonescu", "MobGap"),
    "GsdAdaptiveIonescu": ("GsdAdaptiveIonescu", "MobGap"),
    "GsdIluz": ("GsdIluz", "MobGap"),
    "GsdIluz_orig_peak": ("GsdIluz", "MobGap (original peak)"),
}

# %%
# Loading Results
# ---------------
# The result files add ``orientation`` to the usual TVS index. The standard
# validation loader keeps unknown CSV columns as data columns, so we can still
# use it for local and remote loading.
local_data_path = (
    Path(get_env_var("MOBGAP_VALIDATION_DATA_PATH")) / "results"
    if int(get_env_var("MOBGAP_VALIDATION_USE_LOCAL_DATA", 0))
    else None
)
__RESULT_VERSION = "main"
loader = ValidationResultLoader(
    "gsd_misorientation",
    result_path=local_data_path,
    version=__RESULT_VERSION,
)

free_living_index_cols = [
    "cohort",
    "participant_id",
    "time_measure",
    "recording",
    "recording_name",
    "recording_name_pretty",
]

lab_index_cols = [
    "cohort",
    "participant_id",
    "time_measure",
    "test",
    "trial",
    "test_name",
    "test_name_pretty",
]

orientation_order = list(REORIENTATION_LABELS)
algorithm_order = [
    f"{algo} ({version})" for algo, version in algorithms.values()
]
cohort_order = ["HA", "CHF", "COPD", "MS", "PD", "PFF"]


def load_condition_results(
    condition: Literal["free_living", "laboratory"],
) -> pd.DataFrame:
    results = []
    for folder_name, (algo, version) in algorithms.items():
        result = (
            loader.load_single_results(folder_name, condition)
            .reset_index()
            .assign(
                algo=algo,
                version=version,
                algo_with_version=f"{algo} ({version})",
            )
        )
        results.append(result)
    return pd.concat(results, ignore_index=True)


free_living_results = load_condition_results("free_living")
lab_results = load_condition_results("laboratory")

# %%
# Plot Helpers
# ------------
sns.set_context("talk")


def plot_f1_by_orientation(data: pd.DataFrame, *, title: str) -> None:
    fig, ax = plt.subplots(figsize=(18, 7), constrained_layout=True)
    sns.boxplot(
        data=data,
        x="algo_with_version",
        y="f1_score",
        hue="orientation",
        order=algorithm_order,
        hue_order=orientation_order,
        showmeans=True,
        ax=ax,
    )
    ax.set_title(title)
    ax.set_xlabel("Algorithm")
    ax.set_ylabel("F1 score")
    ax.set_ylim(-0.02, 1.02)
    ax.tick_params(axis="x", rotation=20)
    ax.grid(True, axis="y", alpha=0.3)
    move_legend_outside(fig, ax, ncol=4)
    plt.show()


def f1_relative_to_identity(
    data: pd.DataFrame, index_cols: list[str]
) -> pd.DataFrame:
    id_cols = [*index_cols, "algo", "version", "algo_with_version"]
    identity = (
        data[data["orientation"] == "identity"][id_cols + ["f1_score"]]
        .rename(columns={"f1_score": "identity_f1_score"})
        .copy()
    )
    return data.merge(identity, on=id_cols, how="left").assign(
        f1_score_delta=lambda df: df["f1_score"] - df["identity_f1_score"]
    )


def plot_f1_delta_by_orientation(data: pd.DataFrame, *, title: str) -> None:
    fig, ax = plt.subplots(figsize=(18, 7), constrained_layout=True)
    sns.boxplot(
        data=data,
        x="algo_with_version",
        y="f1_score_delta",
        hue="orientation",
        order=algorithm_order,
        hue_order=orientation_order,
        showmeans=True,
        ax=ax,
    )
    ax.axhline(0, color="0.4", linewidth=1, linestyle=":", zorder=-50)
    ax.set_title(title)
    ax.set_xlabel("Algorithm")
    ax.set_ylabel("F1 score difference to identity")
    ax.tick_params(axis="x", rotation=20)
    ax.grid(True, axis="y", alpha=0.3)
    move_legend_outside(fig, ax, ncol=4)
    plt.show()


def mean_f1_table(data: pd.DataFrame) -> pd.DataFrame:
    return (
        data.pivot_table(
            index="algo_with_version",
            columns="orientation",
            values="f1_score",
            aggfunc="mean",
            sort=False,
        )
        .reindex(index=algorithm_order, columns=orientation_order)
        .rename_axis(index="Algorithm", columns="Orientation")
    )


# %%
# Free-Living Comparison
# ----------------------
# Every datapoint below is one free-living recording under one simulated
# orientation.
plot_f1_by_orientation(
    free_living_results,
    title="Free-living GSD F1 score by simulated orientation",
)

mean_f1_table(free_living_results)

# %%
# F1 Difference to Identity
# ~~~~~~~~~~~~~~~~~~~~~~~~~
# This plot removes the recording-level difficulty by comparing every simulated
# orientation to the same algorithm on the same recording in the identity
# orientation.
free_living_relative = f1_relative_to_identity(
    free_living_results,
    free_living_index_cols,
)
plot_f1_delta_by_orientation(
    free_living_relative,
    title="Free-living F1 score difference to identity orientation",
)

# %%
# Per Cohort
# ~~~~~~~~~~
fig, ax = plt.subplots(figsize=(14, 7), constrained_layout=True)
sns.boxplot(
    data=free_living_results,
    x="cohort",
    y="f1_score",
    hue="orientation",
    order=cohort_order,
    hue_order=orientation_order,
    showmeans=True,
    ax=ax,
)
ax.set_title("Free-living GSD F1 score per cohort")
ax.set_xlabel("Cohort")
ax.set_ylabel("F1 score")
ax.set_ylim(-0.02, 1.02)
ax.grid(True, axis="y", alpha=0.3)
move_legend_outside(fig, ax, ncol=4)
plt.show()

# %%
# Laboratory Comparison
# ---------------------
# Every datapoint below is one laboratory trial under one simulated orientation.
plot_f1_by_orientation(
    lab_results,
    title="Laboratory GSD F1 score by simulated orientation",
)

mean_f1_table(lab_results)

# %%
# F1 Difference to Identity
# ~~~~~~~~~~~~~~~~~~~~~~~~~
lab_relative = f1_relative_to_identity(lab_results, lab_index_cols)
plot_f1_delta_by_orientation(
    lab_relative,
    title="Laboratory F1 score difference to identity orientation",
)

# %%
# Per Cohort
# ~~~~~~~~~~
fig, ax = plt.subplots(figsize=(14, 7), constrained_layout=True)
sns.boxplot(
    data=lab_results,
    x="cohort",
    y="f1_score",
    hue="orientation",
    order=cohort_order,
    hue_order=orientation_order,
    showmeans=True,
    ax=ax,
)
ax.set_title("Laboratory GSD F1 score per cohort")
ax.set_xlabel("Cohort")
ax.set_ylabel("F1 score")
ax.set_ylim(-0.02, 1.02)
ax.grid(True, axis="y", alpha=0.3)
move_legend_outside(fig, ax, ncol=4)
plt.show()


# sphinx_gallery_multi_image = "single"
