"""
.. _gsd_misorientation_val_results:

GSD performance under simulated mounting errors
================================================

This analysis compares free-living gait sequence detection performance across
simulated lower-back sensor mounting orientations. It uses the result files
generated by :ref:`gsd_misorientation_val_gen`.

The plots show the per-recording F1 score and the overall number of detected and
true-positive gait sequences for each algorithm and orientation. Each simulated
orientation is produced by converting the TVS recording to body frame and
applying the rough mounting rotations used by the reorientation validation.

.. note::
    The standard GSD validation remains the reference for performance under the
    default Mobilise-D mounting assumption. This page isolates orientation
    robustness and therefore only compares Python algorithms that can be rerun
    on the simulated recordings.

"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from mobgap.data.validation_results import ValidationResultLoader
from mobgap.gait_sequences.evaluation import categorize_intervals
from mobgap.plotting import move_legend_outside
from mobgap.re_orientation.pipeline import REORIENTATION_LABELS
from mobgap.utils.misc import get_env_var

# %%
# Algorithms
# ----------
algorithms = {
    "GsdIonescu": ("GsdIonescu", "MobGap"),
    "GsdIluz": ("GsdIluz", "MobGap"),
    "GsdIluz_orig_peak": ("GsdIluz", "MobGap (original peak)"),
}

# %%
# Loading Results
# ---------------
# The result files add ``orientation`` to the usual TVS index. The standard
# validation loader keeps unknown CSV columns as data columns, so we can still
# use it for local and remote loading.
local_data_path = (
    Path(get_env_var("MOBGAP_VALIDATION_DATA_PATH")) / "results"
    if int(get_env_var("MOBGAP_VALIDATION_USE_LOCAL_DATA", 0))
    else None
)
__RESULT_VERSION = "main"
loader = ValidationResultLoader(
    "gsd_misorientation",
    result_path=local_data_path,
    version=__RESULT_VERSION,
)

free_living_index_cols = [
    "cohort",
    "participant_id",
    "time_measure",
    "recording",
    "recording_name",
    "recording_name_pretty",
]
group_cols = ["fold", *free_living_index_cols, "orientation"]

orientation_order = list(REORIENTATION_LABELS)
algorithm_order = [
    f"{algo} ({version})" for algo, version in algorithms.values()
]


def load_free_living_results() -> pd.DataFrame:
    results = []
    for folder_name, (algo, version) in algorithms.items():
        result = (
            loader.load_single_results(folder_name, "free_living")
            .reset_index()
            .assign(
                algo=algo,
                version=version,
                algo_with_version=f"{algo} ({version})",
                result_folder=folder_name,
            )
        )
        results.append(result)
    return pd.concat(results, ignore_index=True)


def load_raw_free_living_results(
    raw_result_name: str,
) -> dict[str, pd.DataFrame]:
    raw_results = {}
    for folder_name in algorithms:
        try:
            raw_results[folder_name] = (
                loader.load_single_csv_file(
                    folder_name,
                    "free_living",
                    f"raw_{raw_result_name}.csv",
                )
                .reset_index()
                .sort_values(group_cols)
            )
        except FileNotFoundError as e:
            raise FileNotFoundError(
                f"Missing raw_{raw_result_name}.csv for {folder_name}. Re-run "
                "`revalidation/gait_sequences/"
                "_99_gsd_misorientation_result_generation_no_exc.py` "
                "with the current script before running this analysis."
            ) from e
    return raw_results


free_living_results = load_free_living_results()
raw_detected_results = load_raw_free_living_results("detected")
raw_reference_results = load_raw_free_living_results("reference")

# %%
# Plot Helpers
# ------------
sns.set_context("talk")


def plot_f1_by_orientation(data: pd.DataFrame, *, title: str) -> None:
    fig, ax = plt.subplots(figsize=(18, 7), constrained_layout=True)
    sns.boxplot(
        data=data,
        x="algo_with_version",
        y="f1_score",
        hue="orientation",
        order=algorithm_order,
        hue_order=orientation_order,
        showmeans=True,
        ax=ax,
    )
    ax.set_title(title)
    ax.set_xlabel("Algorithm")
    ax.set_ylabel("F1 score")
    ax.set_ylim(-0.02, 1.02)
    ax.tick_params(axis="x", rotation=20)
    ax.grid(True, axis="y", alpha=0.3)
    move_legend_outside(fig, ax, ncol=4)
    plt.show()


def _raw_interval_list(raw_gs_list: pd.DataFrame) -> pd.DataFrame:
    id_columns = [
        c for c in raw_gs_list.columns if c not in {*group_cols, "start", "end"}
    ]
    if len(id_columns) != 1:
        raise ValueError(
            "Expected exactly one raw gait sequence id column, "
            f"found {id_columns}."
        )
    return raw_gs_list.set_index(id_columns[0])[["start", "end"]]


def _empty_interval_list() -> pd.DataFrame:
    return pd.DataFrame(columns=["start", "end"]).rename_axis("gs_id")


def count_tp_gs_per_recording(
    single_results: pd.DataFrame,
    raw_detected: dict[str, pd.DataFrame],
    raw_reference: dict[str, pd.DataFrame],
) -> pd.DataFrame:
    rows = []
    single_result_groups = single_results[
        [*group_cols, "result_folder", "algo_with_version", "detected_num_gs"]
    ].drop_duplicates()

    for folder_name, single_result_group in single_result_groups.groupby(
        "result_folder", sort=False
    ):
        detected_by_group = {
            group_label: _raw_interval_list(group)
            for group_label, group in raw_detected[folder_name].groupby(
                group_cols, sort=False
            )
        }
        reference_by_group = {
            group_label: _raw_interval_list(group)
            for group_label, group in raw_reference[folder_name].groupby(
                group_cols, sort=False
            )
        }
        for row in single_result_group.itertuples(index=False):
            group_label = tuple(getattr(row, col) for col in group_cols)
            detected = detected_by_group.get(
                group_label, _empty_interval_list()
            )
            reference = reference_by_group.get(
                group_label, _empty_interval_list()
            )
            matches = categorize_intervals(
                gsd_list_detected=detected,
                gsd_list_reference=reference,
                multiindex_warning=False,
            )
            rows.append(
                {
                    "algo_with_version": row.algo_with_version,
                    "orientation": row.orientation,
                    "detected_num_gs": row.detected_num_gs,
                    "tp_num_gs": int((matches["match_type"] == "tp").sum()),
                }
            )

    return (
        pd.DataFrame(rows)
        .groupby(
            ["algo_with_version", "orientation"], as_index=False, sort=False
        )[["detected_num_gs", "tp_num_gs"]]
        .sum()
    )


def plot_gs_counts_by_orientation(data: pd.DataFrame) -> None:
    data_long = data.melt(
        id_vars=["algo_with_version", "orientation"],
        value_vars=["detected_num_gs", "tp_num_gs"],
        var_name="metric",
        value_name="n_gs",
    ).replace(
        {
            "metric": {
                "detected_num_gs": "Detected GSs",
                "tp_num_gs": "TP GSs",
            }
        }
    )
    fig, axes = plt.subplots(
        1,
        len(algorithm_order),
        figsize=(22, 7),
        sharey=True,
        constrained_layout=True,
    )
    for ax, algo_name in zip(axes, algorithm_order):
        sns.barplot(
            data=data_long[data_long["algo_with_version"] == algo_name],
            x="orientation",
            y="n_gs",
            hue="metric",
            order=orientation_order,
            hue_order=["Detected GSs", "TP GSs"],
            ax=ax,
        )
        ax.set_title(algo_name)
        ax.set_xlabel("Orientation")
        ax.set_ylabel("Number of GSs" if ax is axes[0] else "")
        ax.tick_params(axis="x", rotation=45)
        ax.grid(True, axis="y", alpha=0.3)

    handles, labels = axes[0].get_legend_handles_labels()
    for ax in axes:
        legend = ax.get_legend()
        if legend is not None:
            legend.remove()
    fig.legend(
        handles, labels, loc="outside lower center", ncol=2, frameon=False
    )
    plt.show()


def gs_count_table(data: pd.DataFrame) -> pd.DataFrame:
    table_index = pd.MultiIndex.from_product(
        [algorithm_order, orientation_order],
        names=["Algorithm", "Orientation"],
    )
    return (
        data.pivot_table(
            index=["algo_with_version", "orientation"],
            values=["detected_num_gs", "tp_num_gs"],
            aggfunc="sum",
            sort=False,
        )
        .reindex(table_index)
        .rename(
            columns={"detected_num_gs": "Detected GSs", "tp_num_gs": "TP GSs"}
        )
        .astype("Int64")
    )


# %%
# Free-Living Comparison
# ----------------------
# Every datapoint below is one free-living recording under one simulated
# orientation.
plot_f1_by_orientation(
    free_living_results,
    title="Free-living GSD F1 score by simulated orientation",
)

# %%
# Detected and True-Positive GS Counts
# ------------------------------------
# A true-positive GS is a detected gait sequence that overlaps with a reference
# gait sequence by at least 80 % in both directions.
gs_count_summary = count_tp_gs_per_recording(
    free_living_results,
    raw_detected_results,
    raw_reference_results,
)
plot_gs_counts_by_orientation(gs_count_summary)

# %%
gs_count_table(gs_count_summary)

# sphinx_gallery_multi_image = "single"
