"""
.. _wtd_val_results_no_exc:

Performance of the wear-time detection algorithms on the SUSTAIN dataset
========================================================================

This script analyses locally generated, unpublished wear-time validation results for the SUSTAIN wear-time dataset.
It intentionally reads only local files generated by :mod:`revalidation.weartime._02_wtd_result_generation_no_exc`.

.. note:: If you are interested in how these results are calculated, head over to the processing script
    :ref:`wtd_val_gen_no_exc`. These results are not part of the published validation-result package at this time.

"""

# %%
# Compared algorithms
# -------------------
# At the moment, this local validation compares the signal-based wear-time detector implemented in MobGap. Additional
# algorithms can be added here once they are implemented as :class:`~mobgap.weartime.base.BaseWeartimeDetector`
# instances and evaluated with the wear-time result-generation script.
from pathlib import Path

import pandas as pd
from mobgap.utils.misc import get_env_var

algorithms = {
    "WtdMegaritisSignal": ("WtdMegaritisSignal", "MobGap"),
}

results_base_path = Path(get_env_var("MOBGAP_VALIDATION_DATA_PATH")) / "results/weartime_no_exc"
condition_name = "sustain_weartime"
index_cols = ["recording_type", "participant_id", "recording_id", "recording_day"]


def load_single_results(result_name: str) -> pd.DataFrame:
    result_path = results_base_path / condition_name / result_name / "single_results.csv"
    if not result_path.exists():
        raise FileNotFoundError(
            f"Could not find generated wear-time results at {result_path}. "
            "Run revalidation/weartime/_02_wtd_result_generation_no_exc.py first."
        )

    results = pd.read_csv(result_path)
    available_index_cols = [column for column in index_cols if column in results.columns]
    return results.set_index(available_index_cols)


def load_aggregated_results(result_name: str) -> pd.DataFrame:
    result_path = results_base_path / condition_name / result_name / "aggregated_results.csv"
    if not result_path.exists():
        raise FileNotFoundError(
            f"Could not find generated wear-time results at {result_path}. "
            "Run revalidation/weartime/_02_wtd_result_generation_no_exc.py first."
        )

    return pd.read_csv(result_path, index_col=0)


results = pd.concat(
    {display_name: load_single_results(result_name) for result_name, display_name in algorithms.items()},
    names=["algo", "version"],
).reset_index()
results = results.assign(
    algo_with_version=lambda df_: df_["algo"] + " (" + df_["version"] + ")",
    abs_weartime_error_min=lambda df_: df_["weartime_error_min"].abs(),
    abs_waking_weartime_error_min=lambda df_: df_["waking_weartime_error_min"].abs(),
)

aggregated_results = pd.concat(
    {display_name: load_aggregated_results(result_name) for result_name, display_name in algorithms.items()},
    names=["algo", "version"],
)

# %%
# Overview
# --------
# The core classification metrics are calculated from interval overlaps on the sample level. The duration metrics are
# reported in minutes. Waking-hours duration metrics use the same waking-hours configuration as the algorithm.
summary_aggs = {
    "n_datapoints": ("weartime_error_min", "size"),
    "precision_mean": ("precision", "mean"),
    "recall_mean": ("recall", "mean"),
    "f1_score_mean": ("f1_score", "mean"),
    "accuracy_mean": ("accuracy", "mean"),
    "specificity_mean": ("specificity", "mean"),
    "reference_weartime_min_mean": ("reference_weartime_min", "mean"),
    "detected_weartime_min_mean": ("detected_weartime_min", "mean"),
    "weartime_error_min_mean": ("weartime_error_min", "mean"),
    "weartime_error_min_median": ("weartime_error_min", "median"),
    "abs_weartime_error_min_mean": ("abs_weartime_error_min", "mean"),
    "waking_reference_weartime_min_mean": ("waking_reference_weartime_min", "mean"),
    "waking_detected_weartime_min_mean": ("waking_detected_weartime_min", "mean"),
    "waking_weartime_error_min_mean": ("waking_weartime_error_min", "mean"),
    "abs_waking_weartime_error_min_mean": ("abs_waking_weartime_error_min", "mean"),
}

summary_overall = results.groupby(["algo", "version"]).agg(**summary_aggs)
summary_overall

# %%
# Per recording type
# ------------------
# SUSTAIN contains human-movement recordings and simulated-movement recordings. The simulated-movement recordings are
# expected to be reference non-wear across the full selected day.
summary_by_recording_type = results.groupby(["recording_type", "algo", "version"]).agg(**summary_aggs)
summary_by_recording_type

# %%
# Per participant
# ---------------
# The dataset is evaluated per day. This aggregation keeps the recording type and participant identity, then averages
# across the selected participant's days.
summary_by_participant = results.groupby(["recording_type", "participant_id", "algo", "version"]).agg(**summary_aggs)
summary_by_participant

# %%
# Debug plots
# -----------
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(2, 2, figsize=(13, 9))

sns.boxplot(
    data=results,
    x="recording_type",
    y="abs_weartime_error_min",
    hue="algo_with_version",
    ax=axes[0, 0],
    showmeans=True,
)
axes[0, 0].set_title("Absolute overall wear-time error")
axes[0, 0].set_xlabel("")

sns.boxplot(
    data=results,
    x="recording_type",
    y="abs_waking_weartime_error_min",
    hue="algo_with_version",
    ax=axes[0, 1],
    showmeans=True,
)
axes[0, 1].set_title("Absolute waking-hours wear-time error")
axes[0, 1].set_xlabel("")

sns.boxplot(
    data=results,
    x="recording_type",
    y="f1_score",
    hue="algo_with_version",
    ax=axes[1, 0],
    showmeans=True,
)
axes[1, 0].set_title("F1 score")
axes[1, 0].set_xlabel("")

sns.scatterplot(
    data=results,
    x="reference_weartime_min",
    y="detected_weartime_min",
    hue="recording_type",
    style="algo_with_version",
    ax=axes[1, 1],
)
axes[1, 1].set_title("Detected vs reference wear-time")
axes[1, 1].set_xlabel("Reference wear-time [min]")
axes[1, 1].set_ylabel("Detected wear-time [min]")

for ax in axes.flatten():
    legend = ax.get_legend()
    if legend is not None:
        legend.set_title("")

plt.tight_layout()
fig.show()

