"""
.. _wtd_val_results_no_exc:

Performance of the wear-time detection algorithms on the SUSTAIN dataset
========================================================================

.. warning::
    Public wear-time validation data from lower-back sensors is scarce. We therefore tuned and evaluated the wear-time
    algorithm on the same dataset, which may bias the reported performance. If you have access to an independent
    dataset, please test the algorithm and share your results with us.

This script analyses locally generated, unpublished wear-time validation results for the SUSTAIN wear-time dataset.
It intentionally reads only local files generated by :mod:`revalidation.weartime._02_wtd_result_generation_no_exc`.

.. note:: If you are interested in how these results are calculated, head over to the processing script
    :ref:`wtd_val_gen_no_exc`. These results are not part of the published validation-result package at this time.

"""

# %%
# Compared algorithms
# -------------------
# At the moment, this local validation compares the signal-based wear-time detector implemented in MobGap. Additional
# algorithms can be added here once they are implemented as :class:`~mobgap.weartime.base.BaseWeartimeDetector`
# instances and evaluated with the wear-time result-generation script.
from pathlib import Path

import pandas as pd
from mobgap.utils.misc import get_env_var

algorithms = {
    "WtdMegaritisSignal": ("WtdMegaritisSignal", "MobGap"),
}

results_base_path = (
    Path(get_env_var("MOBGAP_VALIDATION_DATA_PATH")) / "results/weartime_no_exc"
)
condition_name = "sustain_weartime"
index_cols = [
    "recording_type",
    "participant_id",
    "recording_id",
    "recording_day",
]


def load_single_results(result_name: str) -> pd.DataFrame:
    result_path = (
        results_base_path / condition_name / result_name / "single_results.csv"
    )
    if not result_path.exists():
        raise FileNotFoundError(
            f"Could not find generated wear-time results at {result_path}. "
            "Run revalidation/weartime/_02_wtd_result_generation_no_exc.py first."
        )

    results = pd.read_csv(result_path)
    available_index_cols = [
        column for column in index_cols if column in results.columns
    ]
    return results.set_index(available_index_cols)


def load_aggregated_results(result_name: str) -> pd.DataFrame:
    result_path = (
        results_base_path
        / condition_name
        / result_name
        / "aggregated_results.csv"
    )
    if not result_path.exists():
        raise FileNotFoundError(
            f"Could not find generated wear-time results at {result_path}. "
            "Run revalidation/weartime/_02_wtd_result_generation_no_exc.py first."
        )

    return pd.read_csv(result_path, index_col=0)


results = pd.concat(
    {
        display_name: load_single_results(result_name)
        for result_name, display_name in algorithms.items()
    },
    names=["algo", "version"],
).reset_index()
results = results.assign(
    algo_with_version=lambda df_: df_["algo"] + " (" + df_["version"] + ")",
    abs_weartime_error_min=lambda df_: df_["weartime_error_min"].abs(),
    abs_waking_weartime_error_min=lambda df_: df_[
        "waking_weartime_error_min"
    ].abs(),
)
human_movement_results = results[results["recording_type"] == "human_movement"]
simulated_nonwear_results = results[
    results["recording_type"] == "simulated_movements"
]

aggregated_results = pd.concat(
    {
        display_name: load_aggregated_results(result_name)
        for result_name, display_name in algorithms.items()
    },
    names=["algo", "version"],
)

# %%
# Overview
# --------
# The core classification metrics are calculated from interval overlaps on the sample level. The duration metrics are
# reported in minutes. Waking-hours duration metrics use the same waking-hours configuration as the algorithm.
human_movement_summary_aggs = {
    "n_days": ("weartime_error_min", "size"),
    "precision_mean": ("precision", "mean"),
    "recall_mean": ("recall", "mean"),
    "f1_score_mean": ("f1_score", "mean"),
    "accuracy_mean": ("accuracy", "mean"),
    "specificity_mean": ("specificity", "mean"),
    "reference_weartime_min_mean": ("reference_weartime_min", "mean"),
    "detected_weartime_min_mean": ("detected_weartime_min", "mean"),
    "weartime_error_min_mean": ("weartime_error_min", "mean"),
    "weartime_error_min_median": ("weartime_error_min", "median"),
    "abs_weartime_error_min_mean": ("abs_weartime_error_min", "mean"),
    "waking_reference_weartime_min_mean": (
        "waking_reference_weartime_min",
        "mean",
    ),
    "waking_detected_weartime_min_mean": (
        "waking_detected_weartime_min",
        "mean",
    ),
    "waking_weartime_error_min_mean": ("waking_weartime_error_min", "mean"),
    "abs_waking_weartime_error_min_mean": (
        "abs_waking_weartime_error_min",
        "mean",
    ),
}

human_movement_summary_overall = human_movement_results.groupby(
    ["algo", "version"]
).agg(**human_movement_summary_aggs)
human_movement_summary_overall

# %%
# Human movement: per participant
# -------------------------------
# For the human-movement recordings we inspect the full set of overlap and duration metrics. The dataset is evaluated
# per day; this aggregation keeps the participant identity, then averages across the selected participant's days.
human_movement_summary_by_participant = human_movement_results.groupby(
    ["participant_id", "algo", "version"]
).agg(**human_movement_summary_aggs)
human_movement_summary_by_participant

# %%
# Simulated non-wear movement
# ---------------------------
# The simulated-movement recordings are reference non-wear across the full selected day. For these datapoints, the
# relevant question is whether the algorithm detected any wear by accident.
simulated_nonwear_summary_aggs = {
    "n_days": ("detected_weartime_min", "size"),
    "n_days_with_detected_wear": (
        "detected_weartime_min",
        lambda series: (series > 0).sum(),
    ),
    "detected_wear_day_fraction": (
        "detected_weartime_min",
        lambda series: (series > 0).mean(),
    ),
    "detected_weartime_min_total": ("detected_weartime_min", "sum"),
    "detected_weartime_min_mean": ("detected_weartime_min", "mean"),
    "detected_weartime_min_median": ("detected_weartime_min", "median"),
    "detected_weartime_min_max": ("detected_weartime_min", "max"),
    "waking_detected_weartime_min_total": (
        "waking_detected_weartime_min",
        "sum",
    ),
    "waking_detected_weartime_min_max": ("waking_detected_weartime_min", "max"),
}

simulated_nonwear_summary_overall = simulated_nonwear_results.groupby(
    ["algo", "version"]
).agg(**simulated_nonwear_summary_aggs)
simulated_nonwear_summary_overall

# %%
# Simulated non-wear: per participant
# -----------------------------------
simulated_nonwear_summary_by_participant = simulated_nonwear_results.groupby(
    ["participant_id", "algo", "version"]
).agg(**simulated_nonwear_summary_aggs)
simulated_nonwear_summary_by_participant

# %%
# Human movement plots
# --------------------
import matplotlib.pyplot as plt
import seaborn as sns

fig_human, axes = plt.subplots(2, 2, figsize=(13, 9))

sns.boxplot(
    data=human_movement_results,
    x="algo_with_version",
    y="abs_weartime_error_min",
    ax=axes[0, 0],
    showmeans=True,
)
axes[0, 0].set_title("Absolute overall wear-time error")
axes[0, 0].set_xlabel("")

sns.boxplot(
    data=human_movement_results,
    x="algo_with_version",
    y="abs_waking_weartime_error_min",
    ax=axes[0, 1],
    showmeans=True,
)
axes[0, 1].set_title("Absolute waking-hours wear-time error")
axes[0, 1].set_xlabel("")

sns.boxplot(
    data=human_movement_results,
    x="algo_with_version",
    y="f1_score",
    ax=axes[1, 0],
    showmeans=True,
)
axes[1, 0].set_title("F1 score")
axes[1, 0].set_xlabel("")

sns.scatterplot(
    data=human_movement_results,
    x="reference_weartime_min",
    y="detected_weartime_min",
    hue="algo_with_version",
    ax=axes[1, 1],
)
axes[1, 1].set_title("Detected vs reference wear-time")
axes[1, 1].set_xlabel("Reference wear-time [min]")
axes[1, 1].set_ylabel("Detected wear-time [min]")

for ax in axes.flatten():
    legend = ax.get_legend()
    if legend is not None:
        legend.set_title("")

plt.tight_layout()
fig_human.show()

# %%
# Simulated non-wear plots
# ------------------------
fig_simulated, axes = plt.subplots(1, 2, figsize=(13, 4))

sns.boxplot(
    data=simulated_nonwear_results,
    x="algo_with_version",
    y="detected_weartime_min",
    ax=axes[0],
    showmeans=True,
)
axes[0].set_title("Accidental detected wear-time")
axes[0].set_xlabel("")
axes[0].set_ylabel("Detected wear-time [min]")

sns.scatterplot(
    data=simulated_nonwear_results,
    x="recording_day",
    y="detected_weartime_min",
    hue="participant_id",
    style="algo_with_version",
    ax=axes[1],
)
axes[1].set_title("Accidental wear detections per simulated day")
axes[1].set_xlabel("Recording day")
axes[1].set_ylabel("Detected wear-time [min]")
axes[1].tick_params(axis="x", rotation=45)

for ax in axes.flatten():
    legend = ax.get_legend()
    if legend is not None:
        legend.set_title("")

plt.tight_layout()
fig_simulated.show()
